# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
   - task: AzureKeyVault@2
     inputs:
       azureSubscription: 'ags-az(1)(286d8ce0-9043-45a8-871e-f25fe6c7aa5d)'
       KeyVaultName: 'variableaccestodevops'
       SecretsFilter: '*'
       RunAsPreJob: false
   - bash: echo $(DATABASE-PASSWD)   
 


# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'
